module.exports = {
  mySidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Installation',
      items: [
        'install/quickstart',
        'install/requirements',
        'install/configuration',
        'install/methods',
        'install/private_registry',
        'install/registry_mirror',
        'install/airgap',
        'install/ha',
        'install/windows_airgap',
        'install/server_roles',
        'install/packaged_components',
        'install/uninstall',
      ],
    },
    {
      type: 'category',
      label: 'Upgrades',
      items:[
        {
          type: 'doc',
          id: 'upgrades/upgrade',
          label: 'Overview',
        },
        'upgrades/manual_upgrade',
        'upgrades/automated_upgrade',
        'upgrades/roll-back',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items:[
        'security/about_hardened_images',
        'security/hardening_guide',
        'security/cis_self_assessment110',
        'security/cis_self_assessment19',
        'security/cis_self_assessment18',
        'security/fips_support',
        'security/pod_security_standards',
        'security/selinux',
        'security/secrets_encryption',
        'security/certificates',
        'security/token',
      ],
    },
    {
      type: 'category',
      label: 'Datastore',
      items: [
        'datastore/embedded',
        'datastore/external',
        'datastore/backup_restore',
      ],
    },
    {
      type: 'doc',
      id: 'architecture',
      label: 'Architecture',
    },
    'cluster_access',
    {
      type: 'category',
      label: 'Networking',
      items: [
        'networking/basic_network_options',
        'networking/multus_sriov',
        'networking/networking_services',
        'networking/windows_bgp',
      ],
    },
    {
      type: 'category',
      label: 'Add-ons',
      items: [
        'add-ons/helm',
        'add-ons/import-images',
        'add-ons/gpu_operators',
      ],
    },
    'advanced',
    {
      type: 'category',
      label: 'Reference',
      items:[
        {
          type: 'autogenerated',
          dirName: 'reference', // Generate sidebar slice from docs/architecture
        },
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'release-notes',
        },
        {
          type: 'category',
          label: 'Older...',
          items: [
            {
              type: 'autogenerated',
              dirName: 'release-notes-old',
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'known_issues',
      label: 'Known Issues',
    }
  ],
};
