module.exports = {
  mySidebar: [
    'index',
    {
      type: 'category',
      label: 'Installation',
      items: [
        'install/quickstart',
        'install/requirements',
        'install/configuration',
        'install/network_options',
        'install/ha',
        'install/methods',
        'install/containerd_registry_configuration',
        'install/airgap',
        'install/windows_airgap',
        'install/linux_uninstall',
        'install/windows_uninstall',
      ],
    },
    {
      type: 'category',
      label: 'Upgrades',
      items:[
        'upgrade/upgrade',
        'upgrade/basic_upgrade',
        'upgrade/automated_upgrade',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items:[
        'security/about_hardened_images',
        'security/hardening_guide',
        'security/cis_self_assessment15',
        'security/cis_self_assessment16',
        'security/fips_support',
        'security/policies',
        'security/selinux',
        'security/secrets_encryption',
      ],
    },
    'architecture',
    'cluster_access',
    'backup_restore',
    'networking',
    'helm',
    'advanced',
    {
      type: 'category',
      label: 'Reference',
      items:[
        {
          type: 'autogenerated',
          dirName: 'reference', // Generate sidebar slice from docs/architecture
        },
      ],
    },
    'known_issues',
  ],
};