// node ./scripts/sidebar_to_nav.js
// This script generates a nav.adoc file from the Docusaurus sidebar configuration.
// The nav.adoc file is used to create a table of contents for the antora.
const sidebar = require('../sidebars.js').mySidebar;
const fs = require('fs');
const path = require('path');

function listFiles(dir, prefix = '') {
  const fullDir = path.join('docs', dir);
  if (!fs.existsSync(fullDir)) return '';
  let out = '';
  const files = fs.readdirSync(fullDir)
    .filter(f => f.endsWith('.md'))
    .sort();
  for (const file of files) {
    const base = file.replace(/\.md$/, '');
    out += `${prefix}xref:${dir}/${base}.adoc[]\n`;
  }
  return out;
}

// Depth-first traversal of the sidebar structure,
// generating the appropriate xref level for each entry.
function processEntry(items, depth = 0) {
  let out = '';
  const indent = '*'.repeat(depth + 1) + ' ';
  for (const item of items) {
    if (typeof item === 'string') {
      out += `${indent}xref:${item}.adoc[]\n`;
    } else if (item.type === 'category') {
      out += `\n`;
      out += `${'*'.repeat(depth + 1)} ${item.label}\n`;
      out += processEntry(item.items, depth + 1);
    } else if (item.type === 'doc') {
      out += `${indent}xref:${item.id}.adoc[${item.label}]\n`; 
    }else if (item.type === 'autogenerated') {
      out += listFiles(item.dirName, '*'.repeat(depth + 1) + ' ');
    }
  }
  return out;
}

const nav = processEntry(sidebar, 0);
fs.writeFileSync('nav.adoc', nav);
console.log('nav.adoc generated');