= Metrics

import Label from '@site/src/components/Label';

RKE2 provides metrics for monitoring the health and performance of the cluster.

Individual components provide most metrics. See the following component-specific documentation for more information:

* https://coredns.io/plugins/metrics/[CoreDNS metrics]
* https://etcd.io/docs/v3.5/metrics/[etcd metrics]
* https://kubernetes.io/docs/reference/instrumentation/node-metrics/[Kubernetes node metrics]
* https://kubernetes.io/docs/reference/instrumentation/metrics/[Kubernetes component metrics]

Other components may provide additional metrics. Consult the upstream project documentation for any components not listed above.

== Supervisor Metrics

When you start RKE2 with `supervisor-metrics: true`, the RKE2 supervisor exposes metrics. You can access these metrics through the `/metrics` endpoint on each node at port `9345`:

[,sh]
----
kubectl get --server https://NODENAME:9345 --raw /metrics
----

Metrics exposed by the RKE2 supervisor process include:

* <<_rke2_cluster_management_metrics,RKE2 Cluster Management Metrics>>
* https://github.com/rancher/lasso/blob/main/README.md#lasso-controller[Lasso controller metrics]
* https://github.com/kubernetes/client-go/blob/master/README.md[Kubernetes client and workqueue metrics]
* https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics[Go runtime metrics]
* If the RKE2 embedded registry is enabled, https://spegel.dev/docs/metrics/[Spegel metrics] and https://github.com/libp2p/go-libp2p/blob/master/README.md[libp2p metrics]

== RKE2 Cluster Management Metrics

=== rke2_certificate_expiration_seconds

Remaining lifetime in seconds of the certificate, labeled by certificate subject and usages.

* Type: Gauge
* Labels: +++<label>+++subject+++</label>+++ +++<label>+++usage+++</label>+++

=== rke2_loadbalancer_server_connections

Count of current connections to the loadbalancer server, labeled by loadbalancer name and server address.

* Type: Gauge
* Labels: +++<label>+++name+++</label>+++ +++<label>+++server+++</label>+++

=== rke2_loadbalancer_server_health

Current health state of loadbalancer backend servers, labeled by loadbalancer name and server address.

State is enum of 0=INVALID, 1=FAILED, 2=STANDBY, 3=UNCHECKED, 4=RECOVERING, 5=HEALTHY, 6=PREFERRED, 7=ACTIVE.

* Type: Gauge
* Labels: +++<label>+++name+++</label>+++ +++<label>+++server+++</label>+++

=== rke2_loadbalancer_dial_duration_seconds

Time in seconds taken to dial a connection to a backend server, labeled by loadbalancer name and success/failure status.

* Type: Histogram
* Labels: +++<label>+++name+++</label>+++ +++<label>+++status+++</label>+++

=== rke2_etcd_snapshot_save_duration_seconds

Total time in seconds taken to complete the etcd snapshot process, labeled by success/failure status.

* Type: Histrogram
* Labels: +++<label>+++status+++</label>+++

=== rke2_etcd_snapshot_save_local_duration_seconds

Total time in seconds taken to save a local snapshot file, labeled by success/failure status.

* Type: Histrogram
* Labels: +++<label>+++status+++</label>+++

=== rke2_etcd_snapshot_save_s3_duration_seconds

Total time in seconds taken to upload a snapshot file to S3, labeled by success/failure status.

* Type: Histrogram
* Labels: +++<label>+++status+++</label>+++

=== rke2_etcd_snapshot_reconcile_duration_seconds

Total time in seconds taken to sync the list of etcd snapshots, labeled by success/failure status.

* Type: Histrogram
* Labels: +++<label>+++status+++</label>+++

=== rke2_etcd_snapshot_reconcile_local_duration_seconds

Total time in seconds taken to list local snapshot files, labeled by success/failure status.

* Type: Histrogram
* Labels: +++<label>+++status+++</label>+++

=== rke2_etcd_snapshot_reconcile_s3_duration_seconds

Total time in seconds taken to list S3 snapshot files, labeled by success/failure status.

* Type: Histrogram
* Labels: +++<label>+++status+++</label>+++
